# Generated by Django 5.1.6 on 2025-04-10 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'date')},
        ),
    ]
