# Generated by Django 5.1.6 on 2025-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_checkin_date_alter_checkin_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
