# Generated by Django 5.1.6 on 2025-04-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_team_taskassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
