# Generated by Django 5.1.6 on 2025-06-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_joining',
            field=models.DateField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
