name: Django + Postman API Tests on Ubuntu

on: [push, pull_request]

jobs:
  test-on-ubuntu:
    runs-on: ubuntu-latest
    environment: EMFS  # Access environment-scoped secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Python and Pipenv
      run: |
        pip install pipenv
        cd backend
        pipenv --python $(which python)  # Tell pipenv to use the already installed Python 3.10
        pipenv install


    - name: Run Django migrations
      run: |
        cd backend
        pipenv run python manage.py migrate --settings=backend.test_settings

    - name: Start Django server in background
      run: |
        cd backend
        nohup pipenv run python manage.py runserver 127.0.0.1:8000 --settings=backend.test_settings > server.log 2>&1 &

    - name: Wait for server to start
      run: |
        for i in {1..30}; do
          if curl -s http://127.0.0.1:8000 > /dev/null; then
            echo "✅ Django server is up!"
            break
          fi
          echo "⏳ Waiting for server... ($i/30)"
          sleep 2
          if [ $i -eq 30 ]; then
            echo "❌ Server did not start in time"
            exit 1
          fi
        done

    - name: Decode Postman environment JSON from base64
      run: |
        echo "${{ secrets.POSTMAN_ENV_BASE64 }}" | base64 --decode > backend/local_env.json

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman tests
      run: newman run backend/EMFStest.json -e backend/local_env.json
